FROM ubuntu:18.04

RUN apt-get update && apt-get install -y firefox && apt-get install -y python

RUN mkdir -p /Proyecto_tfg

COPY . /Proyecto_tfg

RUN apt-get install git -y

EXPOSE 3000

RUN pip install --upgrade pip


RUN pip freeze > requirements.txt

CMD /usr/bin/firefox



