FROM python:latest

RUN mkdir -p /Proyecto_tfg

COPY . /Proyecto_tfg

EXPOSE 3000

RUN pip install --upgrade pip

RUN pip freeze > requirements.txt

CMD ["Python","/Proyecto_tfg/BIRDS/GUI.py"]



