version: "3.9"
services:
  miapp:
    build: .

    ports:
      - "3000:3000"
    links:
      - monguito
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tfg
      - MONGO_INITDB_ROOT_PASSWORD=123
  